# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-28 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instagram_users', models.ManyToManyField(related_name='clusters', to='app.InstagramUser')),
            ],
        ),
    ]
